version: "2.2"
services:
  app:
    build: ../splash-server
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: splash/run.py
      FLASK_DEBUG: 1
      SPLASH_SERVER_DIR: /app/splash
    volumes:
      - ../splash-server:/app/splash
    command: flask run --host=0.0.0.0
