# This override file is for development only and should be removed in
# a production system.
version: "2.2"
services:
  web:
    image: nginx
    ports:
    - 80:80
    - 443:443
    - 9200:9200
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
  
  
  
  app:
    build: ../splash-server
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      SPLASH_SERVER_DIR: /app/splash
    volumes:
      - ../splash-server:/app
      - ./app/catalogs.yml:/usr/local/share/intake/catalogs.yml
      - ${INGESTOR_PATH_TO_DATA}:/usr/local/data
    entrypoint: ["flask", "run", "--host=0.0.0.0"]