version: "2.2"
services:
  web:
    image: nginx
    ports:
    - 80:80
    - 443:443
    - 9200:9200
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ../splash-client/dist:/usr/share/nginx/html

  db:
    image: mongo:4.1
    hostname: mongo
    environment:
      - TZ=US/Pacific
    expose:
      - 27017
      - 27018
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - ${MONGO_DB_LOC}:/data/db

## On Linux hosts, you need to set sysctl -w vm.max_map_count=262144
## see: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-prod-cluster-composefile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      # - cluster.name=docker-cluster
      # - bootstrap.memory_lock=true
      #- "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"\
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ELASTIC_DATA_LOC}:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300

  monstache:
    image: rwynn/monstache:rel6
    container_name: monstache
    command: -mongo-url=mongodb://db:27017 -elasticsearch-url=http://elasticsearch:9200 #-direct-read-namespace=db.heartbeat -direct-read-split-max=2
    restart: unless-stopped
    
  app:
    build: 
      context: ../splash-server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      #MONGO_URL: mongodb://172.18.0.5:27017
      LOGLEVEL: DEBUG
      SPLASH_SERVER_DIR: /app/splash
    volumes:
      - ../splash-server/splash:/app/splash
    # entrypoint: [ "python", "server.py", "runserver"]
    #entrypoint: [ "uwsgi", "--socket", "0.0.0.0:3031", "--uid", "uwsgi", "--master", "--processes", "8", "--protocol", "uwsgi", "--wsgi", "server:app", "--stats", "127.0.0.1:1717", "--stats-http"]
    ports:
      - 8000:8000
