version: "2"
services:
  db:
    image: mongo:3.6
    hostname: mongo
    mem_limit: 1024m
    environment:
      - TZ=US/Pacific
    expose:
      - 27017
      - 28018
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", --bind_ip_all]
    volumes:
      - /data/db:/data/db
  elasticsearch:
    image: elasticsearch:1.7
    mem_limit: 1024m
    environment:
      - TZ=US/Pacific
    #volumes:
      #- /opt/data/elasticsearch:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    ports:
      - 80:80
      - 443:443
      - 9200:9200

  app:
    build: 
      context: ./splash-server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    environment:
      #MONGO_URL: mongodb://172.18.0.5:27017
      LOGLEVEL: DEBUG
      SPLASH_SERVER_DIR: /app/splash
    volumes:
      - ./splash-server/splash:/app/splash 
      - ./config.cfg:/app/splash/config.cfg
    # entrypoint: [ "python", "server.py", "runserver"]
    entrypoint: [ "uwsgi", "--socket", "0.0.0.0:3031", "--uid", "uwsgi", "--master", "--processes", "8", "--protocol", "uwsgi", "--wsgi", "server:app", "--stats", "127.0.0.1:1717", "--stats-http"]
    ports:
      - 8000:8000